### ISSUE TITLE
能问下这个驱动的来源吗，看着跟 CoreELEC/uwe5631很像，但缺了BT驱动

### ISSUE THREAD

**Issue by txlos** [KryptonLee/uwe5621ds-aml#1]
我想弄到5.10上编译，有完整的驱动吗

**Comment by ZBXallen** [comment]
+1

**Comment by KryptonLee** [comment]
> 我想弄到5.10上编译，有完整的驱动吗

这个就是Github上流出的安卓版本（Linux 4.9）内核的驱动，个人原因蓝牙驱动还没成功移植，CoreELEC的团队就已经搞好了，所以后面直接用官方的就行。
除非有支持5.X的驱动流出，不然想把4.9的驱动移植过去，难度不比从零开始开发小。

**Comment by ftkey** [comment]
> > 我想弄到5.10上编译，有完整的驱动吗
> 
> 这个就是Github上流出的安卓版本（Linux 4.9）内核的驱动，个人原因蓝牙驱动还没成功移植，CoreELEC的团队就已经搞好了，所以后面直接用官方的就行。 除非有支持5.X的驱动流出，不然想把4.9的驱动移植过去，难度不比从零开始开发小。

CoreELEC/uwe5631-aml 已经有了， 能不能编译一个 lineageos 能用的驱动呀， 我试过直接复制CE过去驱动，没有内核错误，但是配置不一样 启动不了。
